name: Upload to DO Spaces
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ ACCESS_KEY}}
          secret_key: ${{ SECRET_KEY }}
          space_name: ${{ SPACE_NAME }}
          space_region: ${{ SPACE_REGION }}
          source: dist/mdq.min.js
          out_dir: quiz
          versioning: true
          cdn_domain: scripts.compsci.rocks

